import json
import os

output_file = r"c:\Users\Afreh Kriss Ntim\bible\data\TWI\Books\Filipifo.json"

filipifo_data = {
    "Filipifo": {
        "1": {
            "1": "Nwoma yi firi Paulo ne Timoteo a wɔyɛ Kristo Yesu nkoa nkyɛn, Yɛde kɔma Yesu Kristo mu ahotefoɔ ne ahwɛfoɔ ne asomafoɔ a wɔwɔ Filipi no nyinaa:",
            "2": "Adom ne asomdwoeɛ a ɛfiri yɛn Agya Onyankopɔn ne Awurade Yesu Kristo nka mo.",
            "3": "Ɛberɛ biara a mekae mo no, meda Onyankopɔn ase.",
            "4": "Saa ara nso na da biara mede anigyeɛ bɔ mpaeɛ ma mo,",
            "5": "ɛfiri sɛ, ɛfiri da a ɛdi ɛkan de bɛsi sɛsɛɛ no, moaboa me wɔ asɛmpaka no adwumayɛ mu.",
            "6": "Yei enti, megye di yie sɛ, Onyankopɔn a ɔhyɛɛ aseɛ yɛɛ saa adwuma pa yi wɔ mo mu no bɛkɔ so de akɔsi da a Yesu Kristo bɛba no.",
            "7": "Sɛdeɛ mo ho adwene pa wɔ me tirim no enti, sɛ daa mekae mo a, na ne kwan so ara ne no.",
            "8": "Anuanom, mepɛ sɛ mote ase sɛ nneɛma a aba me so nyinaa aboa ama Asɛmpa no atrɛw.",
            "9": "Me mpaeɛ a mebɔ ma mo ne sɛ, ɔdɔ a mode dodɔ mo ho mo ho no mu bɛyɛ den, na mobɛnyini wɔ nimdeɛ ne nteaseɛ mu,",
            "10": "sɛdeɛ ɛbɛyɛ a mobɛhunu deɛ ɛyɛ na da a Kristo bɛba no, moayɛ kronn a obi nka asɛm bi ntia mo.",
            "11": "Moma trenee aba a ɛnam Yesu Kristo so ba no nhyɛ mo ma, na moahyɛ Onyankopɔn anuonyam na moakamfo no.",
            "12": "Anuanom, mepɛ sɛ mote ase sɛ, nneɛma a aba me so no aboa ama Asɛmpa no atrɛw.",
            "13": "Ɛno nti, ahemfi awɛmfoɔ no ne nnipa a aka no nyinaa ahunu sɛ Kristo nti na meda efiase.",
            "14": "Na me npa a meda no ama anuanom pii anya gyidie wɔ Awurade mu, na wɔanya akokoɔduru aka Onyankopɔn asɛm no a wɔnnsuro.",
            "15": "Ɛyɛ nokorɛ sɛ ebinom nam anibereɛ ne akasakasa so ka Kristo ho asɛm, na ebinom nso fi adwene pa mu yɛ saa.",
            "16": "Wɔn a wɔfi ɔdɔ mu yɛ no nim sɛ wɔde me asi ha sɛ menkasa mma Asɛmpa no.",
            "17": "Na wɔn a wɔnam anibereɛ so ka Kristo asɛm no deɛ, wɔn adwene nyɛ, na wɔsusu sɛ wɔde bɛha me wɔ me npa a meda mu no.",
            "18": "Na yei enti m’ani gye na mɛkɔ so ama m’ani agye,",
            "19": "ɛfiri sɛ, menim sɛ mo mpaeɛbɔ ne adom a ɛfiri Yesu Kristo Honhom mmoa mu no enti, wɔbɛgyaa me.",
            "20": "M’aniani ne m’anidasoɔ ne sɛ, m’anim rengu ase wɔ biribiara mu, na mmom, sɛdeɛ ɛteɛ daa no, mede akokoɔduru bɛhyɛ Kristo anuonyam wɔ me nipadua mu, sɛ mete ase o, sɛ mewu o.",
            "21": "Na me deɛ, m'ase a meteɛ ne Kristo, na owuo yɛ me mfasoɔ.",
            "22": "Nanso sɛ mete ase a, mɛtumi ayɛ adwuma a ɛho wɔ mfasoɔ ama Kristo.",
            "23": "Yei adi me aniani. Pɛ na mepɛ sɛ metu firi ewiase ne Kristo kɔtena, ɛfiri sɛ, ɛno mmom na ɛyɛ;",
            "24": "nanso mo enti, sɛ mete ase nso a, anka ɛyɛ.",
            "25": "Minim sɛ me ho hia wɔ asase yi so ha; ɛno nti, mɛtena ha kakra na maboa mo ama moanyin wɔ gyidi mu anya anigye.",
            "26": "Sɛ mesan ba mo nkyɛn a, mobɛnya biribi de ahoahoa mo ho wɔ Kristo Yesu mu.",
            "27": "Seesei, adeɛ a ɛho hia me ne sɛ, biribiara a ɛbɛto mo no, momma mo abrabɔ mfata Kristo Asɛmpa no nko ara, sɛdeɛ ɛbɛyɛ a, sɛ yɛhyia o, sɛ yɛanhyia o, mɛte mo ho asɛm pa sɛ mogyina pintinn na mokura botaeɛ korɔ ne gyidie korɔ wɔ Asɛmpa no ho.",
            "28": "Monnsuro mo atamfoɔ. Biribiara a mobɛyɛ no, momfa akokoɔduru nnyina pintinn. Na yei bɛdi adanseɛ sɛ wɔbɛdi nkoguo na moadi nkonim, ɛfiri sɛ, Onyankopɔn ka mo ho.",
            "29": "Na mo deɛ, ɛnyɛ sɛ wɔadom mo sɛ monni Kristo akyi nko, na mmom, sɛ mobɛhunu amane nso.",
            "30": "Afei mobɛtumi ne me abom ako ɔko a mereko no. Saa ɔko yi na ɛberɛ a atwam no, mekoeɛ no, na megu so reko sɛdeɛ mote no no."
        },
        "2": {
            "1": "Mo nkwa a mowɔ wɔ Kristo mu no hyɛ mo den anaa? Ne dɔ kyekye mo werɛ anaa? Mo ne Honhom no wɔ ayɔnkofa bi anaa? Mowɔ ayamye ne ayamhyehye ma mo ho mo ho anaa?",
            "2": "Sɛ ɛte saa de a, ɛnne munnya adwene koro wɔ ɔdɔ ne Honhom ne botae koro mu na m'anigye awie pɛyɛ.",
            "3": "Monnyɛ pɛsɛmenkominya; monnhoahoa mo ho mfa mpɛ anuonyam hunu. Mommrɛ mo ho ase mma mo ho mo ho na mummu mo yɔnkonom nsen mo ankasa mo ho.",
            "4": "Mommma obiara nnnwen ne nko ara n'ade ho na mmom, onnwen n'afɛfo nso de ho bi.",
            "5": "Momma mo abrabɔ nyinaa nyɛ sɛ Yesu Kristo de no bi.",
            "6": "Ɔno na ɔwɔ Onyankopɔn tebea mu de, nanso wanhyɛ ne ho sɛ ɔne Onyankopɔn bɛyɛ pɛ.",
            "7": "Ɔdanee ne tumi kɛse ne n'anuonyam too nkyɛn. Mmom, ofii ne pɛ mu faa akoa tebea de too ne ho so, bae sɛ onipa bɛyɛɛ n'ade sɛ onipa.",
            "8": "Ɔbrɛɛ ne ho ase, yɛɛ osetie, de koduu owu mu, asɛnnua ho wu mu mpo.",
            "9": "Eyi nti Onyankopɔn maa ne so kɔɔ beae a ɛkorɔn koraa, maa no din a edi din nyinaa so.",
            "10": "Na ɛno nti, sɛ wɔbɔ Yesu din a, ɔsorofo ne asase sofo ne asase asefo nkotodwe nyinaa bɛkotow no.",
            "11": "Na tɛkrɛma nyinaa apae mu aka se, Yesu Kristo ne Awurade, de ahyɛ Agya Onyankopɔn anuonyam.",
            "12": "Enti me nnamfo pa, sɛnea na me ne mo te hɔ a na mutie me no, saa ara nso na bere a minni mo nkyɛn mprempren yi, ɛsɛ sɛ mutie me ara nen. Monkɔ so mfa ahopopo ne suro nyɛ adwuma mfa nwie mo nkwagye ho adwumayɛ,",
            "13": "efisɛ, Onyankopɔn na ɔma mufi mo pɛ mu di dwuma a ɛsɔ n'ani.",
            "14": "Dwuma biara a mubedi no, munnnwiinwii na munnnye ho akyinnye",
            "15": "sɛnea ɛbɛyɛ a wɔnka biribi ntia mo na mobɛyɛ kronn sɛ Onyankopɔn mma pa a wɔte wiase a nkontonpofo ne nnebɔneyɛfo ahyɛ ma tɔ no mu. Ɛsɛ sɛ mohyerɛn wɔ wɔn mu sɛ nsoromma a ɛwɔ soro",
            "16": "wɔ nkwa no ho asɛm a moka kyerɛ wɔn no mu. Sɛ moyɛ saa na Kristo Da no mede mo hoahoa me ho a, na ne kwan so ara nen, efisɛ, ɛbɛda no adi sɛ dwuma a mibedii no anyɛ kwa.",
            "17": "Ebia na ɛsɛ sɛ wohwie me mogya gu sɛ afɔrebɔde ne ɔsom a efi mo gyidi mu. Sɛ ɛba saa a, ɛbɛyɛ anigyesɛm na me ne mo nyinaa na enya saa ahosɛpɛw no.",
            "18": "Saa ara nso na ɛsɛ sɛ mo nso mo ani agye na mo ne me nyinaa anya ahosɛpɛw.",
            "19": "M'adwene ho sɛ, mɛsoma yɛn nua Timoteo mo nkyɛn sɛnea ɛbɛyɛ a me nso mɛnya anigye bere a mate mo ho nsɛm.",
            "20": "Ɔno nko ne obi a ɔwɔ ɔtema ma me na mo ho asɛm nso hia no.",
            "21": "Mo mu biara pɛ ɔno ara ne yiyedi a Yesu Kristo ho asɛm mfa ne ho.",
            "22": "Mo ankasa mudi ho adanse sɛ, wakyerɛ mu a odi; wakyerɛ nso sɛ, ɔne me te sɛ ɔba ne n'agya a wɔaka abom adi Asɛmpa no ho dwuma.",
            "23": "Enti mepɛ sɛ mɛsoma no mo nkyɛn ntɛm ara kɛkɛ sɛ mihu nea ɛbɛto me.",
            "24": "Mewɔ Awurade mu gyidi sɛ me nso mɛba ntɛm ara.",
            "25": "M'adwene ho sɛ, mɛsoma yɛn nua Epafrodito a wayɛ adwuma, na wadi me nkyɛn mu ako na wasom mo sɛ somafo de aboa me no wɔ mo nkyɛn.",
            "26": "Ne ho pere no sɛ obehu mo nyinaa na ɛhaw no nso sɛ motee ne nka sɛ ɔyare.",
            "27": "Ampa ara, na ɔyare a anka ɔreyɛ awu. Nanso Onyankopɔn huu no ne me nso mmɔbɔ, efisɛ, wamma manni awerɛhow.",
            "28": "Me ho peree me yiye sɛ mɛsoma no mo nkyɛn na muhu no a, mo ani asan agye bio na me nso m'awerɛhow to atwa.",
            "29": "Momfa ahosɛpɛw nnye no sɛ onua wɔ Awurade mu. Momfa obu ne nidi mma nnipa a wɔte sɛ ɔno nyinaa,",
            "30": "efisɛ, ɔde ne nkwa bɔɔ afɔre a ɛnam so maa anka ɔrewu ama Kristo adwuma de aboa me a anka morentumi mmoa saa no."
        },
        "3": {
            "1": "Anuanom, asɛm a mede rewie ne sɛ, momma mo ani nnye wɔ Awurade mu. Ɛnhaw me sɛ meti nsɛm a makyerɛw dedaw no mu. Eye ma mo akwankyerɛ.",
            "2": "Hwɛ atoro akyerɛkyerɛfo yiye. Monhwɛ nnebɔneyɛfo no a wɔte sɛ akraman a wɔka se twa na ɛsɛ sɛ onipa twa ne ho sie no yiye.",
            "3": "Ɛyɛ yɛn na ɛnyɛ wɔn na yɛagye twetiatwa ato mu, efisɛ, yɛnam Onyankopɔn Honhom so som no na hyɛ a yɛde yɛn ho ahyɛ Kristo Yesu mu no nti, yenya ahosɛpɛw. Yɛmfa yɛn ho nto amanne so.",
            "4": "Sɛ obi wɔ hɔ a odwen sɛ sɛ ɔde ne ho to amanne so na eye a, anka ɛyɛ me. Bere a midii nnawɔtwe pɛ na wotwaa me twetia. Meyɛ Israelni fi m'awosu mu. Mifi Benyamin abusua a wɔyɛ Hebrifo kronn no mu.",
            "5": "Sɛ wɔka Yudafo mmara sodi ho asɛm nso a, meyɛ Farisini.",
            "6": "Na me ho pere me sɛ mɛtaa Kristo.",
            "7": "Nanso, nneɛma a na mefa no sɛ ɛyɛ mfasoɔ nyinaa no, ɛsiane Kristo enti, ayɛ adehwereɛ.",
            "8": "Nokorɛm no, nea mede me hoahoa me ho no, mayɛ de ahwereɛ agu. Efisɛ, Kristo Yesu ho nimdeɛ a ɛkorɔn no yɛ adeɛ a ɛsom bo sene biribiara. Ɛno nti, magyae ne nyinaa koraa. Mebu no sɛ agyanan gu ahwereɛ mu, na ama manya Kristo.",
            "9": "Na mahyɛ no mu, ɛnyɛ mmara mu trenee a mede me ho akatasoɔ no so, na mmom trenee a efi Onyankopɔn hɔ denam gyidie a yɛwɔ wɔ Kristo mu no so.",
            "10": "Mepɛ sɛ minim Kristo ne ne wusɔreɛ tumi a ɛma ɔde ne ho maa ɔhaw no mu kyɛfa.",
            "11": "Na me nso, metumi anya awusɔreɛ a efi awufo mu.",
            "12": "Ɛnyɛ sɛ madi ne nyinaa nkonim anaa masom Kristo pɛpɛɛpɛ dedaw, na mmom merebɔ mmɔden sɛ mɛkɔ so akɔ anim de adwene a ɛsɛ sɛ ɛbata abrabɔ pa a Kristo frɛɛ me mu no, anya.",
            "13": "Anuanom, mennye nni sɛ madi saa nkonim no. Adeɛ baako a ɛsɛ sɛ meyɛ ne sɛ, ɛsɛ sɛ me werɛ firi m'akyi na meyere me ho sɛdeɛ ɛbɛyɛ a mɛduru deɛ ɛwɔ m'anim no ho.",
            "14": "Yei enti, metu mmirika kɔ m'anim tee na madu ɔsoro botaeɛ no a Onyankopɔn nam Kristo Yesu so afrɛ me no ho.",
            "15": "Enti, momma yɛn mu biara a yɛdwen sɛ yɛayɛ yɛn adwene yie no, yɛnnwen saa ara. Na sɛ mo mu biara wɔ adwene foforɔ a, Onyankopɔn bɛda no adi akyerɛ mo.",
            "16": "Nanso, adeɛ a yɛakyerɛkyerɛ mu no, momma yɛnkɔ so nyɛ adwene baako wɔ mu.",
            "17": "Anuanom, monyɛ me nhwɛsoɔ na monhwɛ wɔn a wɔfa akwan a yɛakyerɛkyerɛ mu no so.",
            "18": "Efisɛ, nnipa pii wɔ hɔ a wɔte sɛ wɔn a wɔko tia Kristo asɛnnua no. Na mede awerɛhoɔ reka mo sɛ, nnipa pii kɔ wɔn bɔne mu.",
            "19": "Wɔn awieɛ yɛ ɔsɛeɛ, wɔn nyame yɛ wɔn yafunu, na wɔde aniwudeɛ hoahoa wɔn ho. Wɔn adwene ne asaase so nneɛma nko ara.",
            "20": "Nanso, yɛn mmara yɛ ɔsoro deɛ, na ɛhɔ na yɛhwɛ Kumi a ɔyɛ Awurade Yesu Kristo.",
            "21": "Ɔno na ɔbɛsesa yɛn nipadua a ɛyɛ mmerɛ no na wɔayɛ no sɛ ne nipadua a anuonyam wɔ mu no, denam tumi a ɔwɔ sɛ ɔde nneɛma nyinaa bɛbrɛ ne ho ase no so."
        },
        "4": {
            "1": "Enti anuanom, medɔ mo na m'ani agyina mo. Moama me ho asan me enti me nso mede mo hoahoa me ho. Adɔfonom, saa na ɛsɛ sɛ mugyina pintinn wɔ Awurade mu.",
            "2": "Euodia ne Sintike, mesrɛ mo, montena ase sɛ anuanom wɔ Awurade mu.",
            "3": "Na wo nso a woka me ho a migye wo di no, mepɛ sɛ woboa saa mmea yi, efisɛ, wɔde wɔn ahoɔden nyinaa aboa me ama Asɛmpa no mu atrɛw a Klemens ne m'ahokafo bi a wɔn din hyɛ Onyankopɔn nkwa nhoma no mu no nso ka ho.",
            "4": "Meka ti mu bio sɛ daa munnya ahosɛpɛw wɔ Awurade mu; mo ho nsɛpɛw mo!",
            "5": "Mommrɛ mo ho ase mma nnipa nyinaa. Ɛrenkyɛ, Awurade bɛba.",
            "6": "Mommma biribiara nnhaw mo. Daa mo mpaebɔ nyinaa mu, momfa koma pa mmisa Onyankopɔn nea ehia mo.",
            "7": "Na Onyankopɔn asomdwoe a ɛtra ade nyinaa so no, bɛhwɛ mo koma ne mo adwene so Kristo Yesu mu.",
            "8": "Anuanom, asɛm a mede rewie ne sɛ, nea ɛyɛ nokware, nea ɛwɔ anuonyam, nea ɛteɛ, nea ɛho tew, nea ɛwɔ ɔdɔ, nea ɛwɔ din pa, sɛ ɔbra pa bi wɔ hɔ a, sɛ ayeyi bi wɔ hɔ a, saa nneɛma yi ho na munnwen.",
            "9": "Nea moasua na moanya afi me nkyɛn wɔ nsɛm ne nneyɛe mu no na monyɛ. Na Onyankopɔn a ɔma yɛn asomdwoe no bɛka mo ho.",
            "10": "M'ani gye wɔ Awurade mu sɛ afei de moakyerɛ ɔdɔ a mode dɔ me. Ɛyɛ nokware sɛ modɔ me de, nanso na munnya ho kwan nkyerɛ saa.",
            "11": "Menka saa asɛm yi nkyerɛ sɛ moapa me, efisɛ, masua ama akokwaw me sɛ tebea biara a mewɔ mu no, mepɛ.",
            "12": "Minim ohia, nim ahonya. Masua saa ahintasɛm yi enti baabiara ne bere biara, sɛ ɔkɔm de me anaa mamee, sɛ mewɔ pii anaa kakraa bi no, mepɛ no saa ara.",
            "13": "Ahoɔden a Kristo de ma me no nti, mitumi gyina tebea biara ano.",
            "14": "Eye sɛ moboaa me wɔ m'amanehunu mu.",
            "15": "Mo Filipifo no ankasa nim pefee sɛ bere a mifii Makedonia a na merefiti Asɛmpa no ka no ase no, mo nko ara ne asafo a moboaa me. Mo nko ara na moka nea minyae ne nea mehweree ho.",
            "16": "Mewɔ Tesalonika no, bere biara a biribi ho behia me no, mode brɛ me.",
            "17": "Ɛnyɛ sɛ ɔpɛ na na mepɛ sɛ minya akyɛde na mmom, nhyira a mubenya wɔ mu na na mepɛ sɛ mihu.",
            "18": "Me nsa aka biribiara a mode abrɛ me ma aboro so. Afei a Epafrodito de akyɛde no nyinaa abrɛ me yi, me nsa aka biribiara a ɛho hia me. Eyinom te sɛ afɔrebɔde huamhuam a wɔbɔ ma Onyankopɔn, na ogye, na n'ani sɔ.",
            "19": "Me Nyankopɔn fi ne nnepa a ɔwɔ wɔ Kristo Yesu mu bɛma mo nea ehia mo nyinaa.",
            "20": "Anuonyam nka yɛn Agya Nyankopɔn daa daa. Amen.",
            "21": "Monykye ahotefo a wɔwɔ Kristo Yesu mu nyinaa. Anuanom a wɔka me ho no kye mo.",
            "22": "Ahotefo nyinaa kye mo, titiriw wɔn a wɔwɔ Kaesare fie no.",
            "23": "Awurade Yesu Kristo adom nka mo honhom. Amen."
        }
    }
}

with open(output_file, "w", encoding="utf-8") as f:
    json.dump(filipifo_data, f, indent=2, ensure_ascii=False)

print(f"Updated {output_file} with Twi text.")
